<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemographicSeeder extends Seeder
{
    public function run()
    {
        DB::table('demographics')->insert([
            [
                'region' => 'Region 1',
                'province' => 'Ilocos Norte',
                'district' => 'District 1',
                'city' => 'San Nicolas',
                'barangay' => 'Agpangi', 
                'evacuation_site' => 'Site A',
                'head_last_name' => 'Doe',
                'head_first_name' => 'John',
                'head_middle_name' => 'M.',
                'extension_name' => null,
                'age' => 45,
                'gender' => 'Male',
                'birthday' => '1979-01-15',
                'birth_place' => 'Ilocos Norte',
                'civil_status' => 'Married',
                'mother_maiden_name' => 'Jane Doe',
                'religion' => 'Roman Catholic',
                'occupation' => 'Farmer',
                'income' => 15000,
                'id_card_presented' => 'Driver\'s License',
                'id_card_number' => 'DL-123456',
                'contact_number' => '09171234567',
                'permanent_address' => '123 Permanent St., San Nicolas',
                'created_at' => now()->subYears(4)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 2',
                'province' => 'Cagayan',
                'district' => 'District 2',
                'city' => 'Tuguegarao',
                'barangay' => 'Calampisawan',
                'evacuation_site' => 'Site B',
                'head_last_name' => 'Smith',
                'head_first_name' => 'Jane',
                'head_middle_name' => 'A.',
                'extension_name' => 'Jr.',
                'age' => 32,
                'gender' => 'Female',
                'birthday' => '1991-03-25',
                'birth_place' => 'Cagayan',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Mary Smith',
                'religion' => 'Iglesia ni Cristo',
                'occupation' => 'Teacher',
                'income' => 20000,
                'id_card_presented' => 'Passport',
                'id_card_number' => 'P-987654',
                'contact_number' => '09281234567',
                'permanent_address' => '456 Permanent St., Tuguegarao',
                'created_at' => now()->subYears(4)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 3',
                'province' => 'Zambales',
                'district' => 'District 3',
                'city' => 'Olongapo',
                'barangay' => 'Dolis',
                'evacuation_site' => 'Site C',
                'head_last_name' => 'Johnson',
                'head_first_name' => 'Alice',
                'head_middle_name' => 'B.',
                'extension_name' => null,
                'age' => 28,
                'gender' => 'Female',
                'birthday' => '1995-05-10',
                'birth_place' => 'Zambales',
                'civil_status' => 'Married',
                'mother_maiden_name' => 'Anna Johnson',
                'religion' => 'Protestant',
                'occupation' => 'Nurse',
                'income' => 30000,
                'id_card_presented' => 'Voter\'s ID',
                'id_card_number' => 'V-654321',
                'contact_number' => '09391234567',
                'permanent_address' => '789 Permanent St., Olongapo',
                'created_at' => now()->subYears(4)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 4',
                'province' => 'Laguna',
                'district' => 'District 4',
                'city' => 'Santa Rosa',
                'barangay' => 'Dolis',
                'evacuation_site' => 'Site D',
                'head_last_name' => 'Garcia',
                'head_first_name' => 'Paul',
                'head_middle_name' => 'C.',
                'extension_name' => null,
                'age' => 40,
                'gender' => 'Male',
                'birthday' => '1983-07-20',
                'birth_place' => 'Laguna',
                'civil_status' => 'Widowed',
                'mother_maiden_name' => 'Laura Garcia',
                'religion' => 'Roman Catholic',
                'occupation' => 'Engineer',
                'income' => 45000,
                'id_card_presented' => 'UMID',
                'id_card_number' => 'U-123987',
                'contact_number' => '09491234567',
                'permanent_address' => '123 Street, Santa Rosa',
                'created_at' => now()->subYears(3)->toDateTimeString(),
                'updated_at' => now(),
            ],
            // Repeat similar entries for 6 more records
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'Menchaca',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(2)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'Menchaca',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(2)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'Patun-an',
                'city' => 'Legazpi',
                'barangay' => 'Barangay 5',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(1)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'Patun-an',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(1)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'Refugio',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(1)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'San Isidro',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(1)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'Lo-ok (Poblacion)',
                'city' => 'Legazpi',
                'barangay' => 'Barangay 5',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now()->subYears(1)->toDateTimeString(),
                'updated_at' => now(),
            ],
            [
                'region' => 'Region 5',
                'province' => 'Bicol',
                'district' => 'District 5',
                'city' => 'Legazpi',
                'barangay' => 'Lo-ok (Poblacion)',
                'evacuation_site' => 'Site E',
                'head_last_name' => 'Perez',
                'head_first_name' => 'Maria',
                'head_middle_name' => 'D.',
                'extension_name' => null,
                'age' => 36,
                'gender' => 'Female',
                'birthday' => '1987-11-12',
                'birth_place' => 'Bicol',
                'civil_status' => 'Single',
                'mother_maiden_name' => 'Susan Perez',
                'religion' => 'Evangelical',
                'occupation' => 'Accountant',
                'income' => 25000,
                'id_card_presented' => 'SSS ID',
                'id_card_number' => 'S-987123',
                'contact_number' => '09501234567',
                'permanent_address' => '456 Street, Legazpi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Continue with additional rows...
        ]);
    }
}
